### ISSUE TITLE
本地运行报错？

### ISSUE THREAD

**Issue by qtencent7** [dxx/react-bilibili#19]

**Comment by dxx** [comment]
详细描述一下或者有没有具体错误信息

**Comment by qtencent7** [comment]
> 详细描述一下或者有没有具体错误信息
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.9.10

Please only submit bug reports when using the officially supported version.

**Comment by dxx** [comment]
项目里面指定 typescript 版本是 `3.2.1`，你的版本太高了。
